import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { useSession } from "../../state/session";
import WorkerMiniDayPicker from "./WorkerMiniDayPicker";
import ProductivityChart from "../Charts/ProductivityChart";
import ComplianceChart from "../Charts/ComplianceChart";
import ReportModal from "../ReportModal";
export default function WorkerHeader3Panel({ anchor, onPickDate, children }) {
    const { user, logout } = useSession();
    const [range, setRange] = useState("week");
    const [pdfModalOpen, setPdfModalOpen] = useState(false);
    return (_jsxs("div", { className: "header3", children: [_jsxs("div", { className: "headerPanel", children: [_jsxs("div", { className: "rowBetween", children: [children ? children : (_jsxs("div", { className: "panelTitle", children: [_jsx("div", { className: "h2", children: user?.full_name || "Ishchi" }), _jsx("div", { className: "muted small", children: user?.phone_login })] })), _jsxs("div", { style: { display: "flex", alignItems: "center", gap: 8 }, children: [_jsx("button", { className: "btn mini", onClick: () => {
                                            const isLight = document.body.classList.toggle("light-mode");
                                            localStorage.setItem("theme", isLight ? "light" : "dark");
                                        }, title: "Mavzu", style: { width: 32, padding: 0 }, children: "\uD83C\uDF13" }), _jsx(WorkerMiniDayPicker, { currentISO: anchor, onPick: onPickDate })] })] }), _jsxs("div", { className: "kpiBox", style: { alignItems: "flex-start", gap: 16 }, children: [_jsxs("div", { style: { display: "flex", flexDirection: "column", alignItems: "center", gap: 6 }, children: [_jsxs("div", { className: "kpi", style: { margin: 0 }, children: [_jsx("div", { className: "kpiLabel", children: "Sana" }), _jsx("div", { className: "kpiValue", children: anchor })] }), _jsx("button", { className: "linkBtn muted", onClick: logout, title: "Chiqish", style: { fontSize: "24px", color: "#666" }, children: _jsx("i", { className: "fa-solid fa-right-from-bracket" }) })] }), _jsxs("div", { className: "kpi", children: [_jsx("div", { className: "kpiLabel", children: "Holat" }), _jsx("div", { className: "kpiValue", style: { color: "#41d17a" }, children: "Faol" })] }), _jsx("button", { className: "linkBtn", onClick: () => setPdfModalOpen(true), title: "Hisobot (PDF)", style: { fontSize: "28px", color: "#41d17a", marginLeft: "4px", marginTop: "8px" }, children: _jsx("i", { className: "fa-solid fa-file-pdf" }) })] })] }), pdfModalOpen && (_jsx(ReportModal, { onClose: () => setPdfModalOpen(false), defaultDate: anchor, isAdmin: false })), _jsxs("div", { className: "headerPanel", children: [_jsxs("div", { className: "rowBetween", children: [_jsx("div", { className: "panelTitle", children: "Unumdorlik" }), _jsx("div", { className: "seg", children: ["week", "month", "year"].map((r) => (_jsx("button", { className: `segBtn ${range === r ? "segOn" : ""}`, onClick: () => setRange(r), children: r === "week" ? "H" : r === "month" ? "O" : "Y" }, r))) })] }), _jsx(ProductivityChart, { range: range, anchor: anchor, workerId: user?.id })] }), _jsxs("div", { className: "headerPanel", children: [_jsx("div", { className: "rowBetween", children: _jsx("div", { className: "panelTitle", children: "Majburiy" }) }), _jsx(ComplianceChart, { range: range, anchor: anchor, workerId: user?.id })] })] }));
}
